CREATE EXTERNAL TABLE HTTP_LOGS_CSV_15GB
(
  HOST STRING,
  METHOD STRING,
  ENDPOINT STRING,
  PROTOCOL STRING,
  STATUS STRING,
  OBJECT_SIZE INT,
  DATE_TIME TIMESTAMP
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;